(() => {
'use strict';
const VERSION = '0.3.0';
const $ = id => document.getElementById(id);
const FLATS = ['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];
const SHARPS = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const IDX = {C:0,'B#':0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,Fb:4,'E#':5,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11,Cb:11};
const FLAT_ROOTS = new Set(['F','Bb','Eb','Ab','Db','Gb','Cb']);
let selected = null, targetRoot = 'C', currentFilter = 'all', editingId = null, wakeLock = null;
function esc(v){return String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function root(k){const m=String(k||'').trim().match(/^([A-G])([#b]?)/);return m?m[1]+(m[2]||''):'C'}
function isMinor(k){return /^([A-G][#b]?)m(?!aj)/.test(String(k||''))}
function displayKey(r,base){return r+(isMinor(base)?'m':'')}
function prefersFlats(k){return FLAT_ROOTS.has(root(k))}
function distance(a,b){return ((IDX[root(b)]??0)-(IDX[root(a)]??0)+12)%12}
function transposeNote(n,semitones,useFlats){const i=IDX[n];if(i==null)return n;return (useFlats?FLATS:SHARPS)[(i+semitones+120)%12]}
function transposeChord(raw,from,to){if(!raw||raw==='%'||raw==='—'||raw==='N.C.'||raw==='NC')return raw;const par=raw.match(/^\((.+)\)$/);if(par)return '('+transposeChord(par[1],from,to)+')';const m=raw.match(/^([A-G])([#b]?)(.*?)(?:\/([A-G])([#b]?))?$/);if(!m)return raw;const semis=distance(from,to),flats=prefersFlats(to),rr=transposeNote(m[1]+(m[2]||''),semis,flats),bb=m[4]?transposeNote(m[4]+(m[5]||''),semis,flats):'';return rr+(m[3]||'')+(bb?'/'+bb:'')}
function parseChart(text){const sections=[];let cur=null;String(text||'').split(/\n/).forEach(raw=>{const line=raw.trim();if(!line)return;const h=line.match(/^\[(.+?)\]$/);if(h){cur={name:h[1].trim(),measures:[]};sections.push(cur);return}if(!cur){cur={name:'A',measures:[]};sections.push(cur)}line.split('|').map(x=>x.trim()).filter(Boolean).forEach(cell=>{const bits=cell.split('::'),music=bits.shift().trim(),annotation=bits.join('::').trim();cur.measures.push({chords:music.split(/\s+/).filter(Boolean),annotation})})});return sections}
function hydrate(s){return {...s,sections:s.sections||parseChart(s.chart)}}
const OFFICIAL=(window.RODA_LIBRARY||[]).map(hydrate);
function getUserSongs(){try{return (JSON.parse(localStorage.getItem('roda.userSongs')||'[]')||[]).map(hydrate)}catch{return []}}
function saveUserSongs(v){localStorage.setItem('roda.userSongs',JSON.stringify(v))}
function allSongs(){return [...OFFICIAL,...getUserSongs()]}
function getIds(key){try{return JSON.parse(localStorage.getItem(key)||'[]')||[]}catch{return []}}
function setIds(key,v){localStorage.setItem(key,JSON.stringify(v))}
function favorites(){return getIds('roda.favorites')} function setlist(){return getIds('roda.setlist')} function contains(arr,id){return arr.includes(id)}
function toggleId(key,id){const a=getIds(key),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);setIds(key,a);renderLibrary();if(selected?.id===id)updateDetailButtons()}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1400)}
function show(id){['home','detail','editor','roda'].forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'auto'})}
function filterSong(s,q,favs,set){const text=(s.title+' '+s.composer).toLowerCase();if(q&&!text.includes(q))return false;if(currentFilter==='favorites')return contains(favs,s.id);if(currentFilter==='setlist')return contains(set,s.id);if(currentFilter==='mine')return !s.official||s.personalBase;return true}
function renderLibrary(){const q=$('searchInput').value.toLowerCase().trim(),favs=favorites(),set=setlist(),songs=allSongs().filter(s=>filterSong(s,q,favs,set));$('songCount').textContent=`${songs.length} ${songs.length===1?'música':'músicas'}`;const list=$('songList');list.innerHTML='';if(!songs.length){list.innerHTML='<div class="empty"><h3>Nada por aqui.</h3><p>Mude o filtro, procure outro nome ou use o botão + para criar sua cifra.</p></div>';return}songs.forEach(s=>{const card=document.createElement('div');card.className='song-card';card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Abrir ${s.title}`);card.innerHTML=`<div class="key-box">${esc(s.baseKey)}</div><div class="song-copy"><div class="song-name">${esc(s.title)}${s.official?'<span class="badge">BASE</span>':s.personalBase?'<span class="badge">SEU</span>':''}</div><div class="song-composer">${esc(s.composer)}</div><div class="song-meta">${esc(s.meter)} · ${esc(s.status||'Minha versão')}</div></div><div class="song-actions"><button class="icon-mini fav" aria-label="Favorito">${contains(favs,s.id)?'★':'☆'}</button><button class="icon-mini set" aria-label="Roda de hoje">${contains(set,s.id)?'✓':'＋'}</button><button class="icon-mini open" aria-label="Abrir">›</button></div>`;const open=()=>openSong(s);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});card.querySelector('.fav').addEventListener('click',e=>{e.stopPropagation();toggleId('roda.favorites',s.id)});card.querySelector('.set').addEventListener('click',e=>{e.stopPropagation();toggleId('roda.setlist',s.id)});card.querySelector('.open').addEventListener('click',e=>{e.stopPropagation();open()});list.appendChild(card)})}
function openSong(s){selected=hydrate(s);targetRoot=root(selected.baseKey);renderDetail();show('detail')}
function renderKeyStrip(){const names=prefersFlats(targetRoot)?FLATS:SHARPS,wrap=$('keyStrip');wrap.innerHTML='';names.forEach(k=>{const b=document.createElement('button');b.textContent=displayKey(k,selected.baseKey);if(k===targetRoot)b.classList.add('active');b.addEventListener('click',()=>{targetRoot=k;renderDetail()});wrap.appendChild(b)})}
function renderChart(container,song){container.innerHTML='';let number=0;song.sections.forEach(sec=>{const block=document.createElement('section'),title=document.createElement('div'),grid=document.createElement('div');title.className='part-title';title.textContent=sec.name;grid.className='measure-grid';sec.measures.forEach(m=>{number++;const cell=document.createElement('div');cell.className='measure';const chords=m.chords.map(c=>esc(transposeChord(c,song.baseKey,targetRoot))).join('&nbsp;&nbsp; ');cell.innerHTML=`<span class="measure-no">${number}</span><div class="chords">${chords||'—'}</div>${m.annotation?`<div class="annotation">${esc(m.annotation)}</div>`:''}`;grid.appendChild(cell)});block.append(title,grid);container.appendChild(block)})}
function updateDetailButtons(){$('favoriteBtn').textContent=(contains(favorites(),selected.id)?'★':'☆')+' Favorito';$('setlistBtn').textContent=(contains(setlist(),selected.id)?'✓':'＋')+' Roda de hoje';$('editBtn').textContent=selected.official?'Duplicar para editar':'Editar'}
function renderSources(){$('sourceText').textContent=selected.source||'Cifra criada neste aparelho.';$('songNotes').textContent=selected.notes||'';const links=$('sourceLinks');links.innerHTML='';(selected.sources||[]).forEach(([label,url])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=label;links.appendChild(a)})}
function renderDetail(){$('detailTitle').textContent=selected.title;$('detailComposer').textContent=selected.composer;$('detailMeta').textContent=[selected.meter,selected.form].filter(Boolean).join(' · ');const k=displayKey(targetRoot,selected.baseKey);$('detailKey').textContent=k;$('currentKey').textContent=k;$('baseKeyLabel').textContent='Tom-base: '+selected.baseKey;$('statusLabel').textContent=selected.status||'Minha versão';renderKeyStrip();renderChart($('chart'),selected);renderSources();updateDetailButtons()}
function changeKey(step){const i=IDX[targetRoot]??0,next=(i+step+12)%12;targetRoot=(prefersFlats(targetRoot)?FLATS:SHARPS)[next];renderDetail()}
function changeFont(step){let v=parseInt(localStorage.getItem('roda.font')||'19',10)+step;v=Math.max(14,Math.min(32,v));localStorage.setItem('roda.font',v);document.documentElement.style.setProperty('--chord-size',v+'px');toast(`Cifra ${v}px`)}
function cycleColumns(){let v=parseInt(localStorage.getItem('roda.cols')||'4',10);v=v===4?3:v===3?2:4;localStorage.setItem('roda.cols',v);document.documentElement.style.setProperty('--cols',v);toast(`${v} compassos por linha`)}
async function enterRoda(){$('rodaTitle').textContent=selected.title;$('rodaComposer').textContent=selected.composer;$('rodaKey').textContent=displayKey(targetRoot,selected.baseKey);renderChart($('rodaChart'),selected);show('roda');try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function leaveRoda(){try{if(wakeLock)await wakeLock.release()}catch{}wakeLock=null;renderDetail();show('detail')}
function serialize(sections){return sections.map(s=>'['+s.name+']\n'+s.measures.map(m=>m.chords.join(' ')+(m.annotation?' :: '+m.annotation:'')).join(' | ')).join('\n\n')}
function openEditor(song=null){const editable=song&&!song.official?song:null;editingId=editable?.id||null;$('editorTitle').textContent=editable?'Editar cifra':song?.official?'Duplicar cifra':'Nova cifra';$('editTitle').value=song?.title||'';$('editComposer').value=song?.composer||'';$('editKey').value=song?.baseKey||'C';$('editMeter').value=song?.meter||'2/4';$('editForm').value=song?.form||'';$('editChart').value=song?serialize(song.sections):'[A]\nC | A7 | Dm7 G7 | C\n\n[B]\nF | Fm6 | C A7 | Dm7 G7';previewEditor();show('editor')}
function previewEditor(){const sections=parseChart($('editChart').value),temp={baseKey:$('editKey').value||'C',sections},old=targetRoot;targetRoot=root(temp.baseKey);renderChart($('preview'),temp);targetRoot=old;$('previewCount').textContent=sections.reduce((n,s)=>n+s.measures.length,0)+' compassos'}
function saveEditedSong(){const title=$('editTitle').value.trim(),sections=parseChart($('editChart').value);if(!title)return alert('Dê um título para a música.');if(!sections.some(s=>s.measures.length))return alert('Adicione pelo menos um compasso.');const users=getUserSongs(),obj={id:editingId||'user-'+Date.now(),official:false,title,composer:$('editComposer').value.trim()||'Não informado',baseKey:$('editKey').value.trim()||'C',meter:$('editMeter').value.trim()||'2/4',form:$('editForm').value.trim(),status:'Minha versão',source:'Cifra criada/alterada por você neste aparelho.',notes:'',sources:[],sections};const i=users.findIndex(x=>x.id===obj.id);if(i>=0)users[i]=obj;else users.push(obj);saveUserSongs(users);selected=obj;targetRoot=root(obj.baseKey);renderLibrary();renderDetail();show('detail');toast('Música salva')}
function setFilter(f){currentFilter=f;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderLibrary()}
$('searchInput').addEventListener('input',renderLibrary);$('addSong').addEventListener('click',()=>openEditor());$('backHome').addEventListener('click',()=>{renderLibrary();show('home')});$('rodaMode').addEventListener('click',enterRoda);$('closeRoda').addEventListener('click',leaveRoda);$('keyDown').addEventListener('click',()=>changeKey(-1));$('keyUp').addEventListener('click',()=>changeKey(1));$('fontDown').addEventListener('click',()=>changeFont(-2));$('fontUp').addEventListener('click',()=>changeFont(2));$('layoutBtn').addEventListener('click',cycleColumns);$('favoriteBtn').addEventListener('click',()=>toggleId('roda.favorites',selected.id));$('setlistBtn').addEventListener('click',()=>toggleId('roda.setlist',selected.id));$('editBtn').addEventListener('click',()=>openEditor(selected));$('cancelEdit').addEventListener('click',()=>selected?show('detail'):show('home'));$('saveSong').addEventListener('click',saveEditedSong);$('editChart').addEventListener('input',previewEditor);$('editKey').addEventListener('input',previewEditor);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
document.documentElement.style.setProperty('--chord-size',(localStorage.getItem('roda.font')||19)+'px');document.documentElement.style.setProperty('--cols',localStorage.getItem('roda.cols')||4);renderLibrary();previewEditor();
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js?v=3');reg.update()}catch{}})}
console.info('RODA',VERSION);
})();